
import { Injectable } from '@nestjs/common';
import { PrismaService } from '../../shared/infrastructure/prisma/prisma.service';
import { IClubRepository } from '../domain/repositories/IClubRepository';
import { Club } from '../domain/club.entity';
import { ClubMapper } from './mappers/club.mapper';

@Injectable()
export class PrismaClubRepository implements IClubRepository {
    constructor(private readonly prisma: PrismaService) { }

    async create(club: Club): Promise<Club> {
        const data = ClubMapper.toPersistence(club);
        const created = await this.prisma.club.create({
            data: {
                id: undefined, // Let DB generate UUID if not provided, or let Prisma handle default.
                // Actually, schema says @default(uuid()).
                // So we can omit ID if it's new. But domain entity has ID?
                // DDD: Entity ID should be generated before saving or by DB.uuid.
                // Let's rely on Prisma default if ID is not set, but the Domain Entity has ID in constructor.
                // If the ID is null/undefined in domain, we generate it?
                // Let's assume the ID is generated by UUID library in the service before calling repo.create?
                // Or let Prisma generate it.
                // The Club entity has readonly id.
                // If I pass a new ID, Prisma uses it.
                name: data.name,
                mode: data.mode,
            }
        });
        return ClubMapper.toDomain(created);
    }

    async findById(id: string): Promise<Club | null> {
        const club = await this.prisma.club.findUnique({ where: { id } });
        if (!club) return null;
        return ClubMapper.toDomain(club);
    }

    async findAll(): Promise<Club[]> {
        const clubs = await this.prisma.club.findMany();
        return clubs.map(ClubMapper.toDomain);
    }

    async update(club: Club): Promise<Club> {
        const data = ClubMapper.toPersistence(club);
        const updated = await this.prisma.club.update({
            where: { id: club.id },
            data: {
                name: data.name,
                mode: data.mode,
            },
        });
        return ClubMapper.toDomain(updated);
    }
}
