
import { Injectable } from '@nestjs/common';
import { PrismaService } from '../../shared/infrastructure/prisma/prisma.service';
import { IPersonRepository } from '../domain/repositories/IPersonRepository';
import { Person } from '../domain/person.entity';
import { PersonMapper } from './mappers/person.mapper';

@Injectable()
export class PrismaPersonRepository implements IPersonRepository {
    constructor(private readonly prisma: PrismaService) { }

    async create(person: Person): Promise<Person> {
        const data = PersonMapper.toPersistence(person);
        const created = await this.prisma.person.create({
            data: {
                // Assume ID generated by caller or handle undefined.
                // If caller uses crypto.randomUUID(), we pass id.
                fullName: data.fullName,
                email: data.email,
                phone: data.phone,
            }
        });
        return PersonMapper.toDomain(created);
    }

    async findById(id: string): Promise<Person | null> {
        const person = await this.prisma.person.findUnique({ where: { id } });
        if (!person) return null;
        return PersonMapper.toDomain(person);
    }

    async findAll(): Promise<Person[]> {
        const people = await this.prisma.person.findMany();
        return people.map(PersonMapper.toDomain);
    }

    async update(person: Person): Promise<Person> {
        const data = PersonMapper.toPersistence(person);
        const updated = await this.prisma.person.update({
            where: { id: person.id },
            data: {
                fullName: data.fullName,
                email: data.email,
                phone: data.phone,
            },
        });
        return PersonMapper.toDomain(updated);
    }
}
